# -*- coding: utf-8 -*-
"""projeto-dio-translator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tj7zTHD69bc1yTfApdO0wwIhiHpolqhG
"""

!pip install requests python-docx

import requests
from docx import Document
import os

key = "minha_key"
endpoint = "https://api.cognitive.microsofttranslator.com/"
location = "eastus2"

target_language = 'pt-br'

def traduzir_txt(texto, target_language):
    path = '/translate'
    constructed_url = endpoint + path
    headers = {
        'Ocp-Apim-Subscription-Key': key,
        'Ocp-Apim-Subscription-Region': location,
        'Content-type': 'application/json',
        'X-ClientTraceId': str(os.urandom(16))
    }

    body = [{
        'text': texto
    }]

    params = {
        'api-version': '3.0',
        'from': 'en',
        'to': target_language
    }

    request = requests.post(constructed_url, params=params, headers=headers, json=body)
    response = request.json()
    traduzido = response[0]['translations'][0]['text']
    return traduzido

def traduzir_doc(path):
  documento = Document(path)
  full_txt = []
  for paragrafo in documento.paragraphs:
    texto_traduzido = traduzir_txt(paragrafo.text, target_language)
    full_txt.append(texto_traduzido)

  translated_doc = Document()
  for line in full_txt:
    translated_doc.add_paragraph(line)
  path_translated = path.replace(".docx", f"_{target_language}.docx")
  translated_doc.save(path_translated)
  return path_translated

input_file = '/content/musica.docx'

traduzir_doc(input_file)